input:
  label: "kinesis_input_stream"
  aws_kinesis:
    streams: ["benthos-kinesis-source"]
    dynamodb:
      table: "kinesis-benthos-control"
      create: true
      billing_mode: PROVISIONED
      read_capacity_units: 5
      write_capacity_units: 5
    checkpoint_limit: 1024
    commit_period: 5s
    start_from_oldest: true
    region: us-east-1
    credentials:
      id: "${AWS_ACCOUNT_ID}"
      secret: "${AWS_SECRET}"
    batching:
      count: 10
      period: 10s

pipeline:
  processors:
    - branch:
        processors:
          - aws_lambda:
              function: kinesis-processing
              region: us-east-1
              timeout: 5s
              retries: 3
              credentials:
                id: "${AWS_ACCOUNT_ID}"
                secret: "${AWS_SECRET}"

        result_map: |
          root = if meta().exists("lambda_function_error") {
            throw("Invocation failed due to %v: %v".format(this.errorType, this.errorMessage))
          } else {
            this
          }

output:
  aws_kinesis:
    stream: "benthos-kinesis-target"
    partition_key: "benthos"
    region: us-east-1
    credentials:
      id: "${AWS_ACCOUNT_ID}"
      secret: "${AWS_SECRET}"
